From centos:7

MAINTAINER linker

WORKDIR /linker/router
RUN yum -y install protobuf.x86_64 protobuf-c.x86_64 protobuf-c-devel.x86_64

RUN yum install -y python-setuptools && \
    easy_install supervisor

RUN yum -y install tcpdump

ADD supervisord.conf /etc/supervisord.conf

ADD router.tgz /linker/

ADD entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

RUN yum -y install net-tools

EXPOSE 8081/udp 8000-9000

ENTRYPOINT ["/usr/bin/supervisord"]

CMD ["-n", "-c", "/etc/supervisord.conf"]
