From centos:7

MAINTAINER linker

WORKDIR /linker/router

RUN yum -y install protobuf.x86_64 protobuf-c.x86_64 protobuf-c-devel.x86_64

RUN yum install -y python-setuptools && \
    easy_install supervisor

ADD supervisord.conf /etc/supervisord.conf

ADD router.tgz /linker/

ADD entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

EXPOSE 8000-9000

ENTRYPOINT ["/linker/router/router"]

#CMD ["-n", "-c", "/etc/supervisord.conf"]
