From centos:7

MAINTAINER linker

WORKDIR /linker

ADD gnutls-2.8.5-18.el6.x86_64.rpm /linker/gnutls-2.8.5-18.el6.x86_64.rpm
RUN chmod 755 /linker/gnutls-2.8.5-18.el6.x86_64.rpm

RUN rpm -ivh /linker/gnutls-2.8.5-18.el6.x86_64.rpm --force --nodeps

RUN yum -y install protobuf.x86_64 protobuf-c.x86_64 protobuf-c-devel.x86_64
RUN yum install -y lksctp-tools.x86_64 lksctp-tools-devel.x86_64

RUN ln -s /usr/lib64/libtasn1.so.6.2.3 /usr/lib64/libtasn1.so.3
#RUN ln -s /usr/lib64/libgnutls.so.28.41.0 /usr/lib64/libgnutls.so.26

RUN yum install -y openssl

RUN yum install -y python-setuptools && \
    easy_install supervisor

ADD supervisord.conf /etc/supervisord.conf

RUN ln -s /usr/lib64/libprotobuf-c.so.1 /usr/lib64/libprotobuf-c.so.0

#ADD libgnutls.so.28.41.0 /usr/lib64/libgnutls.so.26

ADD stack.tgz /linker/

ADD entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

EXPOSE 3868 3869 7000-8000

ENTRYPOINT ["/usr/bin/supervisord"]

CMD ["-n", "-c", "/etc/supervisord.conf"]